---
- name: configure ec2 wordpress
  hosts: all
  gather_facts: false
  vars:
    - db_name: wpdb
    - db_user: admin
    - db_pass: tele20483
    - db_host: 
  tasks:
    - name: download wordpress 
      ansible.builtin.get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /etc/wp-latest.tar.gz

    - name: extract wordpress
      ansible.builtin.unarchive:
        src: /etc/wp-latest.tar.gz
        dest: /etc/
        remote_src: true

    - name: move wp files
      shell: mv /etc/wordpress/* /var/www/html

    - name: download auth info
      ansible.builtin.get_url:
        url: https://api.wordpress.org/secret-key/1.1/salt/
        dest: /home/ec2-user/wp-auth

    - name: get contents of file
      slurp:
        src: "/home/ec2-user/wp-auth"
      register: db_auth

    - name: decode file
      set_fact:
        db_auth: "{{ db_auth.content | b64decode }}"
    
    - name: template wp-config
      ansible.builtin.template:
        src: ./templates/wp-config.j2
        dest: /var/www/html/wp-config.php

    - name: restart httpd
      ansible.builtin.systemd:
        state: restarted
        name: httpd
  